### ISSUE TITLE
Conflicts with CodeMirror editor

### ISSUE THREAD

**Issue by david-it** [david-it/dokuwiki_plugin_codebutton#2]
from [vovpff](https://github.com/vovpff):
"When editor opened every mouse click to line in editor initiate gray message `Copied to clipboard`."

**Comment by david-it** [comment]
The plugin is now escaped when in edit mode

**Comment by vovpff** [comment]
This fix works only in full article edit mode by clicking `Edit page` but when just one sections of article edited bug appears.
`do=draft` also should be ignored

**Comment by david-it** [comment]
Plugin should now escaped for any action mode

**Comment by vovpff** [comment]
I'm so sorry but when section edited bug appears

pls check gif

![cb1](https://user-images.githubusercontent.com/8545791/74229372-4a810000-4cd3-11ea-996b-8daf619d4db5.gif)

**Comment by david-it** [comment]
Thanks for the quick feedback.
I see that escaping the action modes is not enough.
I'm going to modify the copy feature to make it less invasive.

**Comment by david-it** [comment]
Quick patch added for _*/doku.php_

**Comment by vovpff** [comment]
@david-it what you mean?

**Comment by david-it** [comment]
> @david-it what you mean?

The plugin is now inactive also for url docu.php (i.e. with no GET variables, like when you are in section editing mode). 
It seems to work for me.

**Comment by david-it** [comment]
The plugin is now less invasive.
Now an image button appears on the top right corner of code blocks.

**Comment by vovpff** [comment]
@david-it could you provide example of image? Looks like this update (v1.2.2) not work with Bootstrap3 template...

**Comment by david-it** [comment]
I am using the Bootstrap3 template, it should work fine.
Here you find a small screenshot: https://paste.pics/81O99

**Comment by david-it** [comment]
My bad, I left a conflict non solved in the javascript code.

**Comment by david-it** [comment]
It should work now:
https://github.com/david-it/dokuwiki_plugin_codebutton/releases/download/v1.2.2/v1.2.2.zip

**Comment by vovpff** [comment]
Thanks. Button is more comfortable because there are ability to copy particular part of code (select by mouse and ctrl+C) or whole code by clicking button. This is coolest plugin for dokuwiki what I know!

**Comment by david-it** [comment]
Thank you for all the feedbacks!
